---
meta:
  size: default
  username: (( vault $CREDENTIALS "/rabbitmq/system:username" ))
  password: (( vault $CREDENTIALS "/rabbitmq/system:password" ))

features:
  use_dns_addresses: true

releases:
  - { name: rabbitmq-forge, version: latest }

stemcells:
- alias: default
  os: ubuntu-bionic
  version: latest

update:
  canaries: 1
  max_in_flight: 10
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

instance_groups:
  - name: standalone
    instances: 1
    azs: [z1]
    networks: [name: (( grab meta.net || 'rabbitmq-services' ))]
    stemcell: default

    vm_type: (( grab meta.size ))

    jobs:
      - name:    rabbitmq
        release: rabbitmq-forge
        properties:
          default_user:     (( grab meta.username ))
          default_password: (( grab meta.password ))
          rabbitmq:
            tls:
              enabled: (( grab meta.rabbitmq.tls.enabled || false ))
              dual-mode: (( grab meta.rabbitmq.tls.dual-mode || false ))
              ca: (( grab meta.rabbitmq.tls.ca || "" ))
              crt: (( grab meta.rabbitmq.tls.crt || "" ))
              key: (( grab meta.rabbitmq.tls.key || "" ))

        provides:
          rabbitmq-servers: { as: rabbitmq-servers,   ip_addresses: false }
        consumes:
          rabbitmq-servers: { from: rabbitmq-servers, ip_addresses: false }
