---
meta:
  size: default
  username: (( vault $CREDENTIALS "/rabbitmq/system:username" ))
  password: (( vault $CREDENTIALS "/rabbitmq/system:password" ))
<% if p("rabbitmq.route_registrar.enabled") -%>
  cf:
    deployment_name: <%= p("cf.deployment_name") %>
<% end -%>

<% if p("rabbitmq.route_registrar.enabled") -%>
params:
   cf:
     core_network: <%= p("cf.core_network") %>
<% end -%>

  environment: <%= p('environment') %>

  cf:
    exodus_path: <%= p('cf.exodus_path') %>
    deployment_name: <%= p('cf.deployment_name') %>
    system_domain: <%= p('cf.system_domain') %>
    api_url:    <%= p('cf.api_url') %>
    username:   <%= p('cf.username') %>
    password:   <%= p('cf.password') %>
  
  mgmt_port:   15671
  mgmt_scheme: https

variables:
- name: rabbitmq_metrics_emitter_ca
  type: certificate
  options:
    is_ca: true
    common_name: (( concat meta.environment "-rabbitmq-metrics-emitter.bosh" ))
- name: rabbitmq_metrics_emitter_crt
  type: certificate
  options:
    ca: rabbitmq_metrics_emitter_ca
    common_name: ((internal_ip))

features:
  use_dns_addresses: true

releases:
  - { name: rabbitmq-forge, version: latest }
<% if p("rabbitmq.route_registrar.enabled") %>
  - { name: routing, version: latest }
  - { name: bpm, version: latest }
  - { name: bosh-dns-aliases, version: latest}
<% end -%>

  - name: loggregator-agent
    version: 6.3.3
    url: https://bosh.io/d/github.com/cloudfoundry/loggregator-agent-release?v=6.3.3
    sha1: e8386f41e967cc609a3e9a1d6ecf674c3c903fb3
  
  - name: rabbitmq-metrics-emitter
    version: 0.4.1
    url:     https://github.com/starkandwayne/rabbitmq-metrics-emitter-release/releases/download/v0.4.1/rabbitmq-metrics-emitter-0.4.1.tgz
    sha1:    05afc6f3559f45e0696c6a3760242045640e0df8

stemcells:
- alias: default
  os: ubuntu-bionic
  version: latest

update:
  canaries: 1
  max_in_flight: 10
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

instance_groups:
- name: standalone
  instances: 1
  azs: [z1]
  networks: [name: (( grab meta.net || "rabbitmq-service" ))]
  stemcell: default

  vm_type: (( grab meta.size ))

  jobs:
  - name:    rabbitmq
    release: rabbitmq-forge
    properties:
      rabbitmq:
        vhost: (( grab meta.params.instance_id || "/" ))
        network: (( grab meta.net || "rabbitmq-service" ))
        default:
          user: rabbit
          password: (( grab meta.password ))
        admin:
          user: (( grab meta.username ))
          pass: (( grab meta.password ))
        tls:
          enabled: (( grab meta.rabbitmq.tls.enabled || false ))
          dual-mode: (( grab meta.rabbitmq.tls.dual-mode || false ))
          ca: (( grab meta.rabbitmq.tls.ca || "" ))
          crt: (( grab meta.rabbitmq.tls.crt || "" ))
          key: (( grab meta.rabbitmq.tls.key || "" ))

    provides:
      rabbitmq-servers:
        as: rabbitmq-servers
        ip_addresses: false

    consumes:
      rabbitmq-servers:
        from: rabbitmq-servers
        ip_addresses: false

<% if p("rabbitmq.route_registrar.enabled") -%>
  - name: route_registrar
    release: routing
    properties:
      nats:
        tls:
          enabled: true
          client_cert: "((/<%= p("bosh.deployment_name") %>-bosh/<%= p("cf.deployment_name") %>/nats_client_cert.certificate))"
          client_key: "((/<%= p("bosh.deployment_name") %>-bosh/<%= p("cf.deployment_name") %>/nats_client_cert.private_key))"
      route_registrar:
        logging_level: "debug"
        routes:
        - name: (( grab name ))
          uris:
           - (( concat name ".<%= p("cf.system_domain") %>" ))
          registration_interval: 10s
<% if p("rabbitmq.route_registrar.tls.enabled") == "true" %>
          tls_port: 15671
          server_cert_domain_san: (( concat name ".<%= p("cf.system_domain") %>" ))
<% else %>
          port: 15672
<% end %>

    consumes:
      nats:
        from: nats
        deployment: <%= p("cf.deployment_name") %>
      nats-tls:
        from: nats-tls
        deployment: <%= p("cf.deployment_name") %>
  - name:  bpm
    release: bpm

addons:
- name: bosh-dns-aliases
  include:
    jobs:
    - name: route_registrar
      release: routing
  jobs:
  - name: bosh-dns-aliases
    release: bosh-dns-aliases
    properties:
      aliases:
      - domain: nats.service.cf.internal
        targets:
        - deployment: (( grab meta.cf.deployment_name ))
          domain: bosh
          instance_group: nats
          network: (( grab params.cf.core_network ))
          query: '*'
      - domain: _.nats.service.cf.internal
        targets:
        - deployment: (( grab meta.cf.deployment_name ))
          domain: bosh
          instance_group: nats
          network: (( grab params.cf.core_network ))
          query: _
<% end %>
      - name:    rabbitmq
        release: rabbitmq-forge
        properties:
          rabbitmq:
            default:
              user: rabbit
              password: (( grab meta.password ))
            admin:
              user: (( grab meta.username ))
              pass: (( grab meta.password ))
            tls:
              enabled: (( grab meta.rabbitmq.tls.enabled || false ))
              dual-mode: (( grab meta.rabbitmq.tls.dual-mode || false ))
              ca: (( grab meta.rabbitmq.tls.ca || "" ))
              crt: (( grab meta.rabbitmq.tls.crt || "" ))
              key: (( grab meta.rabbitmq.tls.key || "" ))

        provides:
          rabbitmq-servers:
            as: rabbitmq-servers
            ip_addresses: false
        consumes:
          rabbitmq-servers:
            from: rabbitmq-servers
            ip_addresses: false

      - name: loggregator_agent
        release: loggregator-agent
        consumes:
          doppler:
            from: doppler
            deployment: (( grab meta.cf.deployment_name ))
        properties:
          loggregator:
            tls:
              ca_cert: (( file "/var/vcap/jobs/rabbitmq-blacksmith-plans/tls/loggregator.ca" ))
              agent:
                cert: (( file "/var/vcap/jobs/rabbitmq-blacksmith-plans/tls/loggregator.crt" ))
                key: (( file "/var/vcap/jobs/rabbitmq-blacksmith-plans/tls/loggregator.key" ))
          metrics:
            server_name: (( concat meta.environment "-rabbitmq-metrics-emitter" ))
            ca_cert: (( rabbitmq_metrics_emitter_ca ))
            cert:    (( rabbitmq_metrics_emitter_crt.certificate ))
            key:     (( rabbitmq_metrics_emitter_crt.key ))

      - name: rabbitmq-metrics-emitter
        release: rabbitmq-metrics-emitter
        properties:
          rabbitmq_metrics_emitter:
            cloud_foundry:
              api:    (( grab meta.cf.api_url ))
              skip_ssl_validation: <%= p('rabbitmq_metrics_emitter.cloud_foundry.skip_ssl_validation') %>
              username: <%= p('rabbitmq_metrics_emitter.cloud_foundry.username') %>
              password: <%= p('rabbitmq_metrics_emitter.cloud_foundry.password') %>
            rmq_management:
              endpoint: (( concat meta.mgmt_scheme "://" jobs.standalone/0.ips[0] ":" meta.mgmt_port "/api" ))
              user: (( grab meta.username ))
              password: (( grab meta.password ))
            loggregator:
              tls:
                cert: (( file "/var/vcap/jobs/rabbitmq-blacksmith-plans/tls/loggregator.crt" ))
                key: (( file "/var/vcap/jobs/rabbitmq-blacksmith-plans/tls/loggregator.key" ))
                ca_cert: (( file "/var/vcap/jobs/rabbitmq-blacksmith-plans/tls/loggregator.ca" ))
