---
credentials:
  dashboard_url: ((  concat "http://" credentials.hostnames[0] ":" credentials.mgmt_port "/#/login/"  meta.username "/" meta.password ))
  rmq_port:   5672
  tls_port:   5671
  mgmt_port: 15672
  hosts:     (( grab jobs.node.ips ))
  vhost: "/"
  username:  (( grab meta.username ))
  password:  (( grab meta.password ))
  uris:      (( cartesian-product "amqp://" meta.username ":" meta.password "@" jobs.node.ips ":" credentials.rmq_port ))
  uri:       (( grab credentials.uris[0] ))
  hostnames: (( grab jobs.node.ips ))
  hostname:  (( grab credentials.hostnames[0] ))
  protocols:
    amqp:
      username:  (( grab meta.username ))
      password:  (( grab meta.password ))
      hosts:     (( grab jobs.node.ips ))
      host:      (( grab credentials.hosts[0] ))
      vhost: "/"
      port: 5672
      ssl: false
      uris:      (( grab credentials.uris ))
      uri:       (( grab credentials.uris[0] ))
    amqp+ssl:
      username:  (( grab meta.username ))
      password:  (( grab meta.password ))
      host:      (( grab jobs.standalone/0.ips[0] ))
      port: 5671
      vhost: "/"
      uri:       (( concat "amqp+ssl://" meta.username ":" meta.password "@" jobs.standalone/0.ips[0] ":" credentials.rmq_port ))
      ssl: true
    management:
      username:  (( grab meta.username ))
      password:  (( grab meta.password ))
      hosts:     (( grab jobs.node.ips ))
      host:      (( grab credentials.hosts[0] ))
      path: "/api"
      port: 15672
      ssl: false
      uris:      (( cartesian-product "http://" meta.username ":" meta.password "@" jobs.node.ips ":" credentials.mgmt_port "/api" ))
      uri:       (( concat "http://" meta.username ":" meta.password "@" credentials.hostnames[0] ":" credentials.mgmt_port "/api" ))
